version: '3.7'
services:
  docsy:
#     build: ./
    image: tsttakakuracr.azurecr.io/docsy-build:latest
    container_name: docsy
    volumes:
      - ./:/app
    working_dir: /app
    ports:
      - 1313:1313
    command:
      - server
