version: '3.7'
services:
  docsy:
    image: tsttakakuracr.azurecr.io/docsy-build:latest
    container_name: docsy-server
    volumes:
      - ./:/app
      - share:/share
    working_dir: /app
    env_file:
      - docker.env
    ports:
      - 1313:1313
    command:
      - server
  pdf:
    image: tsttakakuracr.azurecr.io/html-to-pdf:latest
    container_name: html-to-pdf
    volumes:
      - ./:/app
      - share:/share
    working_dir: /app
    env_file:
      - docker.env
    depends_on:
      - docsy
  docsy-build:
    image: tsttakakuracr.azurecr.io/docsy-build:latest
    container_name: docsy-build
    volumes:
      - ./:/app
      - share:/share
    working_dir: /app
    env_file:
      - docker.env
    command:
      - build
  deploy:
    image: tsttakakuracr.azurecr.io/docsy-build-cli:latest
    container_name: deploy
    volumes:
      - ./:/app
      - share:/share
    working_dir: /app
    env_file:
      - docker.env
    depends_on:
      - docsy-build
volumes:
  share:
