FROM mcr.microsoft.com/azure-cli:2.0.80
WORKDIR /temp

RUN echo -e "\
cd /app \n\
until [ -e /share/updated-git ]; do sleep 1; done; \n\
if [ ! -e .git ]; then \n\
  if [ -e "'$PROJECT'" ]; then \n\
    cd "'$PROJECT'" \n\
  fi \n\
fi \n\
bash run.sh "'dummy $@'" \n\
" > boot.sh

ENTRYPOINT ["bash", "/temp/boot.sh"]

CMD ["deploy"]
